### ISSUE TITLE
Unable to build on iOS

### ISSUE THREAD

**Issue by Greenball233** [Klrohias/unimage-unity#1]
![UC1}JSG4C (XBI9J)9(~8 T](https://github.com/Klrohias/unimage-unity/assets/74454079/3c3eedd5-eb66-450b-ba1f-58f52080193f)

When I tried to build my project, which used Unimage, XCode threw a lot of exceptions.

**Comment by qingyiwebt** [comment]
Fixed in [def03f2](https://github.com/Klrohias/unimage-unity/commit/def03f279da17303647fb35c63a91ae488c5540c)
