### ISSUE TITLE
ངའི་ཨ་མ་ཉིན་ལྟར་ཞོགས་པའི་ཆུ་ཚོད་ལྔ་དང་ཕྱེད་ཀར་ཡར་ལངས་ནས་ང་ལ་གློག་རྡུལ་དུ་བ་བླུགས།

### ISSUE THREAD

**Issue by sobedata** [Klrohias/unimage-unity#2]
ངའི་ཨ་མ་ཉིན་ལྟར་ཞོགས་པའི་ཆུ་ཚོད་ལྔ་དང་ཕྱེད་ཀར་ཡར་ལངས་ནས་ང་ལ་གློག་རྡུལ་དུ་བ་བླུགས།

**Comment by qingyiwebt** [comment]
For convenience and for other people's reference, please use English to send issue.

**Comment by sobedata** [comment]
My mother got up at 5: 30 a.m. every day and poured me e-mails.

**Comment by sobedata** [comment]
My mother got up at 5: 30 a.m. every day and poured me e-smoke
